-- Category 테이블 생성
CREATE TABLE IF NOT EXISTS CATEGORIES (
    CATEGORY_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CATEGORY_NAME VARCHAR(255) NOT NULL,
    CATEGORY_DESCRIPTION TEXT DEFAULT '',
    CATEGORY_CREATED_TIME_STAMPS BIGINT DEFAULT EXTRACT(EPOCH FROM NOW()) * 1000,
    CATEGORY_UPDATED_TIME_STAMPS BIGINT DEFAULT EXTRACT(EPOCH FROM NOW()) * 1000
);

-- Category 테이블 인덱스
CREATE INDEX IF NOT EXISTS IDX_CATEGORIES_NAME ON CATEGORIES (CATEGORY_NAME);
CREATE INDEX IF NOT EXISTS IDX_CATEGORIES_CREATED_TIME ON CATEGORIES (CATEGORY_CREATED_TIME_STAMPS);
CREATE INDEX IF NOT EXISTS IDX_CATEGORIES_UPDATED_TIME ON CATEGORIES (CATEGORY_UPDATED_TIME_STAMPS);

-- Product 테이블 생성
CREATE TABLE IF NOT EXISTS PRODUCTS (
    PRODUCT_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PRODUCT_NAME VARCHAR(255) NOT NULL,
    PRODUCT_PRICE BIGINT NOT NULL,
    PRODUCT_STOCK BIGINT NOT NULL,
    PRODUCT_MAIN_IMAGE TEXT DEFAULT '',
    PRODUCT_DESCRIPTION TEXT DEFAULT '',
    PRODUCT_CATEGORY_ID BIGINT NOT NULL,
    PRODUCT_VERSION BIGINT DEFAULT 1,
    PRODUCT_DELETED BOOLEAN DEFAULT FALSE,
    PRODUCT_CREATED_TIME_STAMPS BIGINT DEFAULT EXTRACT(EPOCH FROM NOW()) * 1000,
    PRODUCT_UPDATED_TIME_STAMPS BIGINT DEFAULT EXTRACT(EPOCH FROM NOW()) * 1000,
    FOREIGN KEY (PRODUCT_CATEGORY_ID) REFERENCES CATEGORIES (CATEGORY_ID)
);

-- Product 테이블 인덱스
CREATE INDEX IF NOT EXISTS IDX_PRODUCTS_NAME ON PRODUCTS(PRODUCT_NAME);
CREATE INDEX IF NOT EXISTS IDX_PRODUCTS_PRICE ON PRODUCTS(PRODUCT_PRICE);
CREATE INDEX IF NOT EXISTS IDX_PRODUCTS_STOCK ON PRODUCTS(PRODUCT_STOCK);
CREATE INDEX IF NOT EXISTS IDX_PRODUCTS_CATEGORY_ID ON PRODUCTS(PRODUCT_CATEGORY_ID);
CREATE INDEX IF NOT EXISTS IDX_PRODUCTS_CREATED_TIME ON PRODUCTS(PRODUCT_CREATED_TIME_STAMPS);
CREATE INDEX IF NOT EXISTS IDX_PRODUCTS_UPDATED_TIME ON PRODUCTS(PRODUCT_UPDATED_TIME_STAMPS);
CREATE INDEX IF NOT EXISTS IDX_PRODUCTS_DELETED ON PRODUCTS(PRODUCT_DELETED);
